{
  "settings": {
    "output_dir": "/exports/me-lcco-aml-hpc/output_HAMLET",
    "genomeDir": "/exports/archive/me-lcco-aml-archive/exports/STAR_files/star-2.7.5c_GRCh38.d1.vd1_gencode.v36",
    "gtf": "/exports/archive/me-lcco-aml-archive/exports/STAR_files/gencode.v36.annotation.gtf"
  },
  "samples": {
    "sample_name": {
      "read_groups": {
        "rg_1": {
            "R1": "file_R1",
            "R2": "file_R3"
        }
      }
    },
    "sample_name_2": {
      "read_groups": {
        "rg_1": {
            "R1": "rg_1_file_R1",
            "R2": "rg_1_file_R3"
        },
        "rg_2": {
            "R1": "rg_2_file_R1",
            "R2": "rg_2_file_R3"
        }
      }
    },
    "sample_name_3": {
      "read_groups": {
        "rg_1": {
            "R1": "rg_1_file_R1",
            "R2": "rg_1_file_R3"
        },
        "rg_2": {
            "R1": "rg_2_file_R1",
            "R2": "rg_2_file_R3"
        },
        "rg_3": {
            "R1": "rg_3_file_R1",
            "R2": "rg_3_file_R3"
        }
      }
    },
    "sample_name_4": {
      "read_groups": {
        "rg_1": {
            "R1": "rg_1_file_R1",
            "R2": "rg_1_file_R3"
        },
        "rg_2": {
            "R1": "rg_2_file_R1",
            "R2": "rg_2_file_R3"
        },
        "rg_3": {
            "R1": "rg_3_file_R1",
            "R2": "rg_3_file_R3"
        },
        "rg_4": {
            "R1": "rg_4_file_R1",
            "R2": "rg_4_file_R3"
        }
      }
    },
  }
}
